//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFClient.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Copies()
        {
            this.Readings = new HashSet<Readings>();
        }
    
        public int IdCopy { get; set; }
        public Nullable<int> IdBook { get; set; }
        public string InvNum { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public Nullable<System.DateTime> DecommissionDate { get; set; }
    
        public virtual Books Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Readings> Readings { get; set; }
    }
}
