//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFClient.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Invoice_ID { get; set; }
        public int Contract_ID { get; set; }
        public string Settled { get; set; }
        public string Sum { get; set; }
        public double Sum_inclVAT { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
